apiVersion: v2
name: ecommerce-app
description: E-commerce application Helm chart for Azure AKS
version: 0.1.0
appVersion: "1.0.0"

# TODO: Add the following metadata:
# - keywords (e.g., ecommerce, azure, microservices)
# - home URL 
# - sources URLs
# - maintainers information

# TODO: Add dependencies if using external charts
# dependencies:
#   - name: redis
#     version: "17.11.3"
#     repository: "https://charts.bitnami.com/bitnami" 
#     condition: redis.enabled
#   - name: postgresql
#     version: "12.8.0"
#     repository: "https://charts.bitnami.com/bitnami"
#     condition: postgresql.enabled

# TODO: Add annotations for Artifact Hub
# annotations:
#   "artifacthub.io/containsSecurityUpdates": "false"
#   "artifacthub.io/changes": |
#     - Initial release
#     - Azure integration
#     - Security hardening