# Frontend Deployment for E-commerce Application
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-frontend
  namespace: ecommerce-app
  labels:
    app: ecommerce
    component: frontend
    app.kubernetes.io/name: ecommerce
    app.kubernetes.io/component: frontend
    app.kubernetes.io/instance: ecommerce-app
    app.kubernetes.io/version: "1.0.0"
spec:
  replicas: 3  # 3 replicas as specified in README
  selector:
    matchLabels:
      app: ecommerce
      component: frontend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: ecommerce
        component: frontend
        app.kubernetes.io/name: ecommerce
        app.kubernetes.io/component: frontend
        app.kubernetes.io/instance: ecommerce-app
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3000"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: ecommerce-sa
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        fsGroup: 1001
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: frontend
        image: acrecommercedev.azurecr.io/ecommerce-frontend:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 3000
          protocol: TCP
        env:
        - name: REACT_APP_API_URL
          value: "http://ecommerce-backend:8080"
        - name: REACT_APP_ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: ecommerce-config
              key: environment
        - name: NODE_ENV
          value: "production"
        resources:
          requests:
            cpu: 100m     # As specified in README
            memory: 128Mi # As specified in README
          limits:
            cpu: 200m     # As specified in README
            memory: 256Mi # As specified in README
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: http
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 0
          periodSeconds: 10
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 30
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1001
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: cache
          mountPath: /var/cache/nginx
        - name: run
          mountPath: /var/run
      volumes:
      - name: tmp
        emptyDir: {}
      - name: cache
        emptyDir: {}
      - name: run
        emptyDir: {}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: ecommerce
                  component: frontend
              topologyKey: kubernetes.io/hostname
      tolerations:
      - key: "node.kubernetes.io/not-ready"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 300
      - key: "node.kubernetes.io/unreachable"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 300
---
# Frontend Service
apiVersion: v1
kind: Service
metadata:
  name: ecommerce-frontend
  namespace: ecommerce-app
  labels:
    app: ecommerce
    component: frontend
    app.kubernetes.io/name: ecommerce
    app.kubernetes.io/component: frontend
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "false"
spec:
  type: ClusterIP  # LoadBalancer specified in README, but ClusterIP for ingress
  selector:
    app: ecommerce
    component: frontend
  ports:
  - name: http
    port: 80
    targetPort: 3000
    protocol: TCP
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
