# Secrets for E-commerce Application
# NOTE: In production, use Azure Key Vault with CSI driver instead of hardcoded secrets
apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-secrets
  namespace: ecommerce-app
  labels:
    app: ecommerce
    app.kubernetes.io/name: ecommerce
    app.kubernetes.io/component: secrets
type: Opaque
stringData:
  # Database connection (placeholder - replace with actual values)
  database-url: "postgresql://pgadmin:password@postgres-server.postgres.database.azure.com:5432/ecommerce_db?sslmode=require"
  
  # Redis connection (if using Azure Redis Cache)
  redis-url: "redis://ecommerce-redis:6379"
  
  # Application secrets
  app-secret-key: "change-this-secret-key-in-production"
  jwt-secret: "change-this-jwt-secret-in-production"
  
  # Azure Workload Identity (optional)
  azure-client-id: "00000000-0000-0000-0000-000000000000"
  azure-tenant-id: "00000000-0000-0000-0000-000000000000"
---
# Image Pull Secret for ACR
apiVersion: v1
kind: Secret
metadata:
  name: acr-secret
  namespace: ecommerce-app
  labels:
    app: ecommerce
type: kubernetes.io/dockerconfigjson
data:
  # This should be created automatically by Azure AD Pod Identity or Workload Identity
  # Manual creation for testing only
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJhY3JlY29tbWVyY2VkZXYuYXp1cmVjci5pbyI6IHsKICAgICAgInVzZXJuYW1lIjogIjAwMDAwMDAwLTAwMDAtMDAwMC0wMDAwLTAwMDAwMDAwMDAwMCIsCiAgICAgICJwYXNzd29yZCI6ICJjaGFuZ2UtdGhpcyIsCiAgICAgICJlbWFpbCI6ICJkZXZvcHNAZXhhbXBsZS5jb20iLAogICAgICAiYXV0aCI6ICJNREF3TURBd01EQXRNREF3TUMwd01EQXdMVEF3TURBdE1EQXdNREF3TURBd01EQXdPbU5vWVc1blpTMTBhR2x6IgogICAgfQogIH0KfQ==
