version: '3.8'

services:
  frontend:
    build: 
      context: ./frontend
      target: production
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:8080

  backend:
    build: 
      context: ./backend
      target: production
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://ecommerce:password@postgres:5432/ecommerce_db
      - REDIS_URL=redis://redis:6379

  postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=ecommerce_db
      - POSTGRES_USER=ecommerce
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
